FROM nvidia/cuda:8.0-cudnn6-runtime-ubuntu16.04

MAINTAINER Institute of Computer Software, Nanjing University <icsnju@163.com>

ENV APT_INSTALL="apt-get install -y --no-install-recommends"
ENV PIP_INSTALL="pip --no-cache-dir install --upgrade"

RUN rm -rf /var/lib/apt/lists/* \
     	   /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list &&\
    apt-get update &&\

    # tools
    $APT_INSTALL curl git wget rsync unzip bzip2 \
      libglib2.0-0 libgl1-mesa-glx libgl1-mesa-dev &&\

    # Anaconda
    curl -s -k https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -O &&\
    bash Anaconda3-5.0.1-Linux-x86_64.sh -b -p /opt/anaconda3   &&\
    rm   Anaconda3-5.0.1-Linux-x86_64.sh     &&\
    echo 'export PATH=/opt/anaconda3/bin:$PATH' >> /etc/profile &&\
    export PATH=/opt/anaconda3/bin:$PATH     &&\  
    conda update  -y -n base conda           &&\   
    conda install -y matplotlib colour numpy &&\
    pip   install pyqt5                      &&\
    apt-get clean && apt-get autoremove      &&\
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*  

RUN conda install -y tensorflow-gpu keras-gpu 

# Set environment
ENV PATH=/opt/anaconda3/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

EXPOSE 6006 8888
